/*
 Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n-1)/2	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n-1)	 	1, 6, 15, 28, 45, ...
It can be verified that t285 = p165 = h143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
 */
package triangular;

public class Tringular 
{

	 
	public static void main(String[] args) 
	{
		 
		long triang = 286;
		long penta = 166;
		long hexa = 144;
		
		  while (true) 
		  {
		   
			  long triangle = triang * (triang + 1) / 2;
		   
			  long pentagon = penta * (penta * 3 - 1) / 2;
		   
			  long hexagon  = hexa * (hexa * 2 - 1);
		   
			  long min = triangle;
		   
		   
			  if(pentagon < min )
			   min = pentagon;
		   
		   
			  else if(hexagon < min)
			   min = hexagon;
		   
		   if (min == triangle && min == pentagon && min == hexagon)
		    {
			   System.out.println(min);
			   break;
		    }
		   
		   if (min == triangle) 
			   triang++;
		   
		   if (min == pentagon) 
			   penta++;
		   
		   if (min == hexagon ) 
			   hexa++;
		   
		  }
	}
}